-- =========================================
-- Project: Grondmatching – definitive schema.sql
-- Matches: models.py + current Supabase DB
-- =========================================

BEGIN;

-- =========================================
-- ENUM: match_status
-- =========================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'match_status') THEN
    CREATE TYPE match_status AS ENUM ('pending', 'approved', 'rejected');
  END IF;
END$$;

-- =========================================
-- COMPANY
-- =========================================
CREATE TABLE IF NOT EXISTS public.company (
  id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(200) NOT NULL UNIQUE,
  email VARCHAR(320) NOT NULL
);

-- =========================================
-- CLIENT
-- =========================================
CREATE TABLE IF NOT EXISTS public.client (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT NOT NULL REFERENCES public.company(id),
  name       VARCHAR(200) NOT NULL,
  email      VARCHAR(320) NOT NULL,
  address    VARCHAR(300) NOT NULL,
  location   VARCHAR(200) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_client_company_id ON public.client(company_id);

-- =========================================
-- GROUND
-- =========================================
CREATE TABLE IF NOT EXISTS public.ground (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location         VARCHAR(200) NOT NULL,
  address          VARCHAR(300) NOT NULL,
  m2               INT NOT NULL,
  budget           NUMERIC(12,2) NOT NULL,
  subdivision_type VARCHAR(120) NOT NULL,
  owner            VARCHAR(200) NOT NULL,
  provider         VARCHAR(200) NOT NULL,
  image_url        TEXT NOT NULL,

  CONSTRAINT ck_ground_m2_nonnegative     CHECK (m2 >= 0),
  CONSTRAINT ck_ground_budget_nonnegative CHECK (budget >= 0)
);

-- =========================================
-- PREFERENCES (1-op-1 met client)
-- =========================================
CREATE TABLE IF NOT EXISTS public.preferences (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        INT NOT NULL UNIQUE REFERENCES public.client(id) ON DELETE CASCADE,
  location         VARCHAR(200) NOT NULL,
  subdivision_type VARCHAR(120) NOT NULL,
  min_m2           INT NOT NULL,
  max_m2           INT NOT NULL,
  min_budget       NUMERIC(12,2) NOT NULL,
  max_budget       NUMERIC(12,2) NOT NULL,

  CONSTRAINT ck_preferences_m2_range
      CHECK (min_m2 <= max_m2),
  CONSTRAINT ck_preferences_budget_range
      CHECK (min_budget <= max_budget)
);

-- =========================================
-- MATCH
-- =========================================
CREATE TABLE IF NOT EXISTS public.match (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id      INT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
  ground_id      INT NOT NULL REFERENCES public.ground(id) ON DELETE CASCADE,
  status         match_status NOT NULL DEFAULT 'pending',

  m2_score       DOUBLE PRECISION NOT NULL,
  budget_score   DOUBLE PRECISION NOT NULL,
  location_score DOUBLE PRECISION NOT NULL,
  type_score     DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_match_client_id ON public.match(client_id);
CREATE INDEX IF NOT EXISTS idx_match_ground_id ON public.match(ground_id);
CREATE INDEX IF NOT EXISTS idx_match_status    ON public.match(status);

COMMIT;
